plugins {
    id 'com.android.application'
}

android {
    namespace 'com.winxpro'
    compileSdk 34

    defaultConfig {
        applicationId 'com.winxpro'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0.0'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    flavorDimensions "app"
    productFlavors {
        n999 {
            dimension "app"
            applicationId "com.winxpro.n999"
            resValue "string", "app_name", "N999"
            resValue "string", "app_id", "n999"
        }
        y999 {
            dimension "app"
            applicationId "com.winxpro.y999"
            resValue "string", "app_name", "Y999"
            resValue "string", "app_id", "y999"
        }
        winpkr {
            dimension "app"
            applicationId "com.winxpro.winpkr"
            resValue "string", "app_name", "WinPkr"
            resValue "string", "app_id", "winpkr"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.browser:browser:1.8.0'
    implementation 'androidx.webkit:webkit:1.10.0'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
